acm-tenant-gitops:
  name: kong-private
  channels:
    infra:
      type: Git
      pathname: https://github.com/finastra-ghe/acm-poc-kong-private-gitops
      secretRef:
        name: acm-github-token
    konghq-helm:
      type: HelmRepo
      pathname: https://charts.konghq.com
