acm-tenant-gitops:
  name: fusion-operate
  channels:
    infra:
      type: Git
      pathname: https://github.com/finastra-ghe/acm-poc-fusion-operate-gitops
      secretRef:
        name: acm-github-token
    helm:
      type: HelmRepo
      pathname: https://finastra-ghe.github.io/acm-poc-system-charts/
