acm-tenant-gitops:
  name: acm-poc-data-engineering-gitops
  channels:
    infra:
      type: Git
      pathname: https://github.com/finastra-engineering/acm-poc-data-engineering-gitops
      secretRef:
        name: acm-github-token
    sample-quarkus-app-helm:
      type: HelmRepo
      pathname: https://finastra-engineering.github.io/sample-quarkus-app-chart
    # uat-northeu-1:
    #   clusterSelector:
    #     matchLabels:
    #       zone: uat-northeu-1
    # uat-westeu-1:
    #   clusterSelector:
    #     matchLabels:
    #       zone: uat-westeu-1
    # prod-eastus-1:
    #   clusterSelector:
    #     matchLabels:
    #       zone: prod-eastus-1
    # prod-westus-1:
    #   clusterSelector:
    #     matchLabels:
    #       zone: prod-westus-1
