---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: {{ include "chart.name" . }}
  namespace: {{ include "chart.name" . }}
  labels:
    acm-app: {{ include "chart.name" . }}-gitops
spec:
  channel: {{ include "chart.name" . }}-ch-infra/channel
  placement:
    local: true
